GET http://127.0.0.1:8080/api/v1/health
Accept: application/json

### get api docs in json format
GET http://127.0.0.1:8080/v3/api-docs

### by two timestamps
POST http://127.0.0.1:8080/api/v1/capacityInTimeRange
Content-Type: application/json

{
  "electricity_farm_id": 1,
  "time_range": {
    "from": "2021-07-05T14:00:00.000000",
    "to": "2021-07-05T19:00:00.000000"
  }
}

### by two timestamps
POST http://127.0.0.1:8080/api/v1/capacityInTimeRange
Content-Type: application/json

{
  "electricity_farm_id": null,
  "time_range": {
    "from": "2021-07-05T10:00:00.000000",
    "to": "2021-07-05T14:00:00.000000"
  }
}

### WRONG timestamps
POST http://127.0.0.1:8080/api/v1/capacityInTimeRange
Content-Type: application/json

{
  "electricity_farm_id": 1,
  "time_range": {
    "from": "2021-07-05T10:00:00.000000",
    "to": "2019-07-05T10:00:00.000000"
  }
}

### by two timestamps
POST http://127.0.0.1:8080/api/v1/capacitiesForTimeRangesList
Content-Type: application/json

{
  "electricity_farm_id": 1,
  "time_ranges": [
    {
      "from": "2021-07-05T14:00:00.000000",
      "to": "2021-07-05T19:00:00.000000"
    },
    {
      "from": "2021-07-05T10:00:00.000000",
      "to": "2021-07-05T14:00:00.000000"
    }
  ]
}
